#!/usr/bin/env node
// Generates dist/ from tokens/*.json.
//
//   node scripts/build.mjs           writes dist/
//   node scripts/build.mjs --check   fails when dist/ does not match the tokens
//
// No dependencies, and dist/ is committed: whoever installs the package from a
// git tag gets the files ready, with no build step.
import { existsSync, mkdirSync, readdirSync, readFileSync, realpathSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const HEADER = "Generated by scripts/build.mjs from tokens/. Do not edit by hand.";
const ALIAS = /^\{([^}]+)\}$/;

/** Merges tokens/*.json into one tree. Two files may not define the same top-level group. */
export function loadTokens(dir = join(root, "tokens")) {
  const tree = {};
  for (const file of readdirSync(dir).sort()) {
    if (!file.endsWith(".json")) continue;
    const groups = JSON.parse(readFileSync(join(dir, file), "utf8"));
    for (const [name, group] of Object.entries(groups)) {
      if (name in tree) throw new Error(`O grupo "${name}" aparece em mais de um arquivo de tokens (${file}).`);
      tree[name] = group;
    }
  }
  return tree;
}

/**
 * The flat list of tokens: path, resolved value, type inherited from the group,
 * description and extensions.
 */
export function flatten(tree) {
  const tokens = [];
  const walk = (node, path, type) => {
    const ownType = node.$type ?? type;
    if ("$value" in node) {
      tokens.push({
        path,
        type: ownType,
        value: resolveValue(node.$value, tree, path),
        description: node.$description,
        extensions: node.$extensions?.tone ?? {},
      });
      return;
    }
    for (const [key, child] of Object.entries(node)) {
      if (key.startsWith("$")) continue;
      if (child === null || typeof child !== "object" || Array.isArray(child)) {
        throw new Error(`${[...path, key].join(".")} não é um token: falta "$value".`);
      }
      walk(child, [...path, key], ownType);
    }
  };
  walk(tree, [], undefined);
  return tokens;
}

/** Replaces each "{group.name}" with the value of the token it points to, inside composite values too. */
function resolveValue(value, tree, from, seen = []) {
  if (typeof value === "string") {
    const alias = value.match(ALIAS);
    if (!alias) return value;
    const target = alias[1];
    if (seen.includes(target)) throw new Error(`Referência circular em ${from.join(".")}: ${[...seen, target].join(" → ")}`);
    const node = target.split(".").reduce((at, key) => at?.[key], tree);
    if (!node || !("$value" in node)) throw new Error(`${from.join(".")} aponta para {${target}}, que não existe.`);
    return resolveValue(node.$value, tree, from, [...seen, target]);
  }
  if (Array.isArray(value)) return value.map((item) => resolveValue(item, tree, from, seen));
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, resolveValue(item, tree, from, seen)]));
  }
  return value;
}

/** The tree with values only: { color: { coral: { 50: "#fff4f2" } } }. */
function nest(tokens) {
  const out = {};
  for (const token of tokens) {
    let at = out;
    for (const key of token.path.slice(0, -1)) {
      at[key] ??= {};
      at = at[key];
    }
    at[token.path.at(-1)] = token.value;
  }
  return out;
}

const kebab = (name) => name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
const px = (value) => `${value}px`;
const rem = (value) => `${value / 16}rem`;
const ms = (value) => `${value}ms`;
const bezier = (points) => `cubic-bezier(${points.join(", ")})`;
const quoted = (family) => (/\s/.test(family) ? `"${family}"` : family);

/** The floor of a clamp() in px (1rem = 16px): the size a phone gets. */
function floorPx(fontSize) {
  const first = String(fontSize).match(/^(?:clamp\(\s*)?([\d.]+)rem/);
  if (!first) throw new Error(`Não sei ler o tamanho "${fontSize}".`);
  return Math.round(Number(first[1]) * 16 * 10) / 10;
}

/** The object dist/index.js and dist/tokens.json export. */
export function buildModel(tree, version) {
  const tokens = flatten(tree);
  const t = nest(tokens);
  const stack = (role) => [quoted(t.font.family[role]), ...t.font.fallback[role]].join(", ");
  const withPhone = (styles) =>
    Object.fromEntries(
      Object.entries(styles).map(([name, style]) => [
        name,
        { ...style, phone: { fontSize: floorPx(style.fontSize), fontWeight: style.fontWeight } },
      ]),
    );
  return {
    version,
    color: t.color,
    neutral: t.neutral,
    fontFamily: t.font.family,
    fontStack: { display: stack("display"), sans: stack("sans") },
    fontWeight: t.font.weight,
    breakpoint: t.breakpoint,
    display: withPhone(t.display),
    text: t.text,
    logo: t.logo,
    space: t.space,
    size: t.size,
    radius: t.radius,
    duration: t.duration,
    easing: { soft: bezier(t.easing.soft), softPoints: t.easing.soft },
    motion: t.motion,
  };
}

// ---------- JavaScript and types ----------

function renderJs(model) {
  const lines = [`// ${HEADER}`, ""];
  for (const [name, value] of Object.entries(model)) {
    lines.push(`export const ${name} = ${JSON.stringify(value, null, 2)};`, "");
  }
  return lines.join("\n");
}

function typeOf(value, indent = "") {
  if (Array.isArray(value)) return `readonly [${value.map((item) => typeOf(item, indent)).join(", ")}]`;
  if (value && typeof value === "object") {
    const inner = `${indent}  `;
    const fields = Object.entries(value).map(
      ([key, item]) => `${inner}readonly ${/^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key)}: ${typeOf(item, inner)};`,
    );
    return `{\n${fields.join("\n")}\n${indent}}`;
  }
  return JSON.stringify(value);
}

function renderTypes(model) {
  const lines = [`// ${HEADER}`, ""];
  for (const [name, value] of Object.entries(model)) {
    lines.push(`export declare const ${name}: ${typeOf(value)};`, "");
  }
  lines.push(
    "/** The colour roles of the neutral ground, the same in light and dark. */",
    "export type NeutralRole = keyof typeof neutral.light;",
    "export type Scheme = keyof typeof neutral;",
    "",
  );
  return lines.join("\n");
}

// ---------- CSS ----------

/**
 * Brand colour declarations. With `bareBase`, the base of each scale loses its
 * number and comes before its steps (`coral`, `coral-50`, ...), the way
 * Tailwind expects; without it every step keeps its number (`coral-500`).
 */
function brandColors(tokens, prefix, { bareBase }) {
  const scales = new Map();
  for (const token of tokens) {
    if (token.path[0] !== "color") continue;
    const [, scale, ...steps] = token.path;
    const isBase = bareBase && token.extensions.base === true;
    const name = [scale, ...(isBase ? [] : steps)].map(kebab).join("-");
    const entries = scales.get(scale) ?? scales.set(scale, []).get(scale);
    if (isBase) entries.unshift([`${prefix}${name}`, token.value]);
    else entries.push([`${prefix}${name}`, token.value]);
  }
  return [...scales.values()].flat();
}

/** Declarations of one scheme of the neutral ground: colours and shadows, each under its own prefix. */
function neutralRoles(tokens, scheme, colorPrefix, shadowPrefix) {
  return tokens
    .filter((token) => token.path[0] === "neutral" && token.path[1] === scheme)
    .map((token) => [`${token.type === "shadow" ? shadowPrefix : colorPrefix}${kebab(token.path[2])}`, token.value]);
}

const declarations = (pairs, indent = "  ") => pairs.map(([name, value]) => `${indent}${name}: ${value};`).join("\n");

function displayUtility(name, style, wide) {
  return [
    `@utility display-${name} {`,
    "  font-family: var(--font-display);",
    `  font-weight: ${style.fontWeight};`,
    `  font-size: ${style.fontSize};`,
    `  line-height: ${style.lineHeight};`,
    `  letter-spacing: ${style.letterSpacing};`,
    `  @media (min-width: ${wide}) {`,
    `    font-weight: ${style.fontWeightWide};`,
    "  }",
    "}",
  ].join("\n");
}

/** Tailwind 4 theme: `@import "@toneorg/design/theme.css";` after `@import "tailwindcss";`. */
function renderTheme(tokens, model) {
  // `next/font` publishes each family in a variable; outside Next the family name applies.
  const font = (role) => {
    const family = model.fontFamily[role];
    const variable = `--font-${family.toLowerCase().replace(/\s+/g, "-")}`;
    const fallback = tokens.find((token) => token.path.join(".") === `font.fallback.${role}`).value;
    return [`var(${variable}, ${quoted(family)})`, ...fallback].join(", ");
  };
  const radii = Object.entries(model.radius)
    // Tailwind already has `rounded-full`.
    .filter(([name]) => name !== "full")
    .map(([name, value]) => [`--radius-${kebab(name)}`, rem(value)]);
  // `text-body`, `text-ui`...: a size with its own line height and weight. `lead` is fluid and ships as a utility.
  const sizes = Object.entries(model.text)
    .filter(([, style]) => typeof style.fontSize === "number")
    .flatMap(([name, style]) => [
      [`--text-${kebab(name)}`, rem(style.fontSize)],
      [`--text-${kebab(name)}--line-height`, rem(style.lineHeight)],
      [`--text-${kebab(name)}--font-weight`, style.fontWeight],
    ]);
  const theme = [
    ...brandColors(tokens, "--color-", { bareBase: true }),
    ...neutralRoles(tokens, "light", "--color-", "--shadow-"),
    ...radii,
    ...sizes,
    ["--font-sans", font("sans")],
    ["--font-display", font("display")],
    ["--ease-soft", model.easing.soft],
  ];
  const utilities = Object.entries(model.display).map(([name, style]) => displayUtility(name, style, model.breakpoint.wide));
  return [
    `/* ${HEADER} */`,
    "",
    "@theme {",
    declarations(theme),
    "}",
    "",
    ...utilities.flatMap((utility) => [utility, ""]),
    "@utility lead {",
    `  font-size: ${model.text.lead.fontSize};`,
    `  line-height: ${model.text.lead.lineHeight};`,
    "}",
    "",
    "/* Press feedback: the control shrinks a little while it is held down. */",
    "@utility press {",
    "  transition-property: scale, background-color, color, box-shadow;",
    `  transition-duration: ${ms(model.duration.fast)};`,
    "  transition-timing-function: var(--ease-soft);",
    "  &:active:not(:disabled) {",
    `    scale: ${model.motion.pressScale};`,
    "  }",
    "  @media (prefers-reduced-motion: reduce) {",
    "    &:active:not(:disabled) {",
    "      scale: 1;",
    "    }",
    "  }",
    "}",
    "",
  ].join("\n");
}

const DARK_SELECTOR = '[data-tone-scheme="dark"]';

function renderThemeDark(tokens) {
  return [
    `/* ${HEADER} */`,
    "",
    "/* The neutral ground in dark. Import after theme.css and mark the element with data-tone-scheme=\"dark\". */",
    `${DARK_SELECTOR} {`,
    declarations(neutralRoles(tokens, "dark", "--color-", "--shadow-")),
    "}",
    "",
  ].join("\n");
}

/** Plain CSS variables, for whoever does not use Tailwind. */
function renderTokensCss(tokens, model) {
  const vars = [
    ...brandColors(tokens, "--tone-", { bareBase: false }),
    ...neutralRoles(tokens, "light", "--tone-", "--tone-shadow-"),
    ...Object.entries(model.radius).map(([name, value]) => [`--tone-radius-${kebab(name)}`, px(value)]),
    ...Object.entries(model.space).map(([name, value]) => [`--tone-space-${kebab(name)}`, px(value)]),
    ...Object.entries(model.size).map(([name, value]) => [`--tone-${kebab(name)}`, px(value)]),
    ["--tone-font-sans", model.fontStack.sans],
    ["--tone-font-display", model.fontStack.display],
    ...Object.entries(model.fontWeight).map(([name, value]) => [`--tone-weight-${kebab(name)}`, value]),
    ...Object.entries(model.duration).map(([name, value]) => [`--tone-duration-${kebab(name)}`, ms(value)]),
    ["--tone-ease-soft", model.easing.soft],
    ["--tone-press-scale", model.motion.pressScale],
  ];
  return [`/* ${HEADER} */`, "", ":root {", declarations(vars), "}", ""].join("\n");
}

function renderTokensCssDark(tokens) {
  return [
    `/* ${HEADER} */`,
    "",
    `${DARK_SELECTOR} {`,
    declarations(neutralRoles(tokens, "dark", "--tone-", "--tone-shadow-")),
    "}",
    "",
  ].join("\n");
}

/** Every file of dist/, by name. */
export function render(tree, version) {
  const tokens = flatten(tree);
  const model = buildModel(tree, version);
  return {
    "index.js": renderJs(model),
    "index.d.ts": renderTypes(model),
    "tokens.json": `${JSON.stringify(model, null, 2)}\n`,
    "theme.css": renderTheme(tokens, model),
    "theme-dark.css": renderThemeDark(tokens),
    "tokens.css": renderTokensCss(tokens, model),
    "tokens-dark.css": renderTokensCssDark(tokens),
  };
}

function main() {
  const check = process.argv.includes("--check");
  const { version } = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
  const files = render(loadTokens(), version);
  const dist = join(root, "dist");
  const stale = [];
  if (!check) mkdirSync(dist, { recursive: true });
  for (const [name, content] of Object.entries(files)) {
    const path = join(dist, name);
    if (check) {
      if (!existsSync(path) || readFileSync(path, "utf8") !== content) stale.push(name);
    } else {
      writeFileSync(path, content);
    }
  }
  if (stale.length > 0) {
    console.error(`dist/ está desatualizado (${stale.join(", ")}). Rode "node scripts/build.mjs" e commite o resultado.`);
    process.exit(1);
  }
  console.log(check ? "dist/ corresponde aos tokens." : `dist/ escrito: ${Object.keys(files).join(", ")}`);
}

// Through node_modules/.bin the path arrives as a symbolic link.
if (process.argv[1] && realpathSync(process.argv[1]) === fileURLToPath(import.meta.url)) main();
